#
# This source file is part of the Stanford LLM on FHIR project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs:
      fastlane_lane:
        description: 'Fastlane lane to run (e.g., beta, userstudy)'
        required: false
        default: 'beta'
        type: string
      googleserviceinfoplistpath:
        description: 'Path to Google Service Info plist file'
        required: false
        default: ''
        type: string

concurrency:
  group: deployment
  cancel-in-progress: false

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    secrets: inherit
  iosapptestflightdeployment:
    name: iOS App TestFlight Deployment
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    permissions:
      contents: read
    with:
      runsonlabels: '["macOS", "self-hosted"]'
      setupsigning: true
      fastlanelane: ${{ inputs.fastlane_lane || 'beta' }}
      googleserviceinfoplistpath: ${{ inputs.googleserviceinfoplistpath || '' }}
    secrets: inherit
