#
# This source file is part of the Stanford LLM on FHIR project
#
# SPDX-FileCopyrightText: 2023 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: Beta Deployment

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  buildandtest:
    name: Build and Test
    uses: ./.github/workflows/build-and-test.yml
    secrets: inherit
  iosapptestflightdeployment:
    name: iOS App TestFlight Deployment
    needs: buildandtest
    uses: StanfordBDHG/.github/.github/workflows/xcodebuild-or-fastlane.yml@v2
    secrets: inherit
    with:
      artifactname: LLMonFHIR.xcresult
      runsonlabels: '["macos-latest"]'
      fastlanelane: beta
      setupsigning: true
