#
# This source file is part of the Stanford LLM on FHIR project
#
# SPDX-FileCopyrightText: 2025 Stanford University
#
# SPDX-License-Identifier: MIT
#

name: User Study Beta Deployment

on:
  workflow_dispatch:

jobs:
  userstudybetadeployment:
    name: User Study Beta Deployment
    uses: ./.github/workflows/beta-deployment.yml
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      fastlane_lane: 'userstudy'
      googleserviceinfoplistpath: 'LLMonFHIR/Supporting Files/UserStudyConfig.plist'
    secrets: inherit
